"use strict";

var makeWrapper = require("./make-wrapper");

module.exports = {
  accounts: makeWrapper("puffs_accounts"),
  blockNumber: makeWrapper("puffs_blockNumber"),
  call: makeWrapper("puffs_call"),
  coinbase: makeWrapper("puffs_coinbase"),
  compileLLL: makeWrapper("puffs_compileLLL"),
  compileSerpent: makeWrapper("puffs_compileSerpent"),
  compileSolidity: makeWrapper("puffs_compileSolidity"),
  estimateGas: makeWrapper("puffs_estimateGas"),
  gasPrice: makeWrapper("puffs_gasPrice"),
  getBalance: makeWrapper("puffs_getBalance"),
  getBlockByHash: makeWrapper("puffs_getBlockByHash"),
  getBlockByNumber: makeWrapper("puffs_getBlockByNumber"),
  getBlockTransactionCountByHash: makeWrapper("puffs_getBlockTransactionCountByHash"),
  getBlockTransactionCountByNumber: makeWrapper("puffs_getBlockTransactionCountByNumber"),
  getCode: makeWrapper("puffs_getCode"),
  getCompilers: makeWrapper("puffs_getCompilers"),
  getFilterChanges: makeWrapper("puffs_getFilterChanges"),
  getFilterLogs: makeWrapper("puffs_getFilterLogs"),
  getLogs: makeWrapper("puffs_getLogs"),
  getStorageAt: makeWrapper("puffs_getStorageAt"),
  getTransactionByBlockHashAndIndex: makeWrapper("puffs_getTransactionByBlockHashAndIndex"),
  getTransactionByBlockNumberAndIndex: makeWrapper("puffs_getTransactionByBlockNumberAndIndex"),
  getTransactionByHash: makeWrapper("puffs_getTransactionByHash"),
  getTransactionCount: makeWrapper("puffs_getTransactionCount"),
  getTransactionReceipt: makeWrapper("puffs_getTransactionReceipt"),
  getUncleByBlockHashAndIndex: makeWrapper("puffs_getUncleByBlockHashAndIndex"),
  getUncleByBlockNumberAndIndex: makeWrapper("puffs_getUncleByBlockNumberAndIndex"),
  getUncleCountByBlockHash: makeWrapper("puffs_getUncleCountByBlockHash"),
  getUncleCountByBlockNumber: makeWrapper("puffs_getUncleCountByBlockNumber"),
  getWork: makeWrapper("puffs_getWork"),
  hashrate: makeWrapper("puffs_hashrate"),
  mining: makeWrapper("puffs_mining"),
  newBlockFilter: makeWrapper("puffs_newBlockFilter"),
  newFilter: makeWrapper("puffs_newFilter"),
  newPendingTransactionFilter: makeWrapper("puffs_newPendingTransactionFilter"),
  protocolVersion: makeWrapper("puffs_protocolVersion"),
  sendRawTransaction: makeWrapper("puffs_sendRawTransaction"),
  sendTransaction: makeWrapper("puffs_sendTransaction"),
  sign: makeWrapper("puffs_sign"),
  signTransaction: makeWrapper("puffs_signTransaction"),
  submitHashrate: makeWrapper("puffs_submitHashrate"),
  submitWork: makeWrapper("puffs_submitWork"),
  subscribe: makeWrapper("puffs_subscribe"),
  syncing: makeWrapper("puffs_syncing"),
  uninstallFilter: makeWrapper("puffs_uninstallFilter"),
  unsubscribe: makeWrapper("puffs_unsubscribe"),
};
